import { WalletConnect, WalletNotice } from './components/WalletConnect';
import { CircuitCall } from './components/CircuitCall';
import { useMidnight } from './hooks/useMidnight';
import { isConfigured } from './config';

export default function App() {
  const session = useMidnight();

  return (
    <div className="shell">
      <header className="rail">
        <span className="rail-mark">Canary</span>
        <dl className="rail-facts">
          <div>
            <dt>Network</dt>
            <dd>{session.targetNetwork}</dd>
          </div>
          <div>
            <dt>Contract</dt>
            <dd>
              <code className="trunc" title={session.contractAddress}>
                {session.contractAddress || 'none'}
              </code>
            </dd>
          </div>
        </dl>
        <span className="rail-spacer" />
        <WalletConnect session={session} />
      </header>

      <WalletNotice session={session} />

      {!isConfigured ? (
        <div className="notice" role="alert">
          <span className="notice-tag">Setup</span>
          <span>No contract address configured.</span>
          <span className="notice-hint">
            Set VITE_CONTRACT_ADDRESS and rebuild. See .env.example.
          </span>
        </div>
      ) : null}

      <main>
        <CircuitCall session={session}>
          {/* The framing for the check-in. Lives inside "your side" on purpose:
              the promise and the act it unlocks belong to the same column. */}
          <p className="eyebrow">
            Weekly pulse · round <b>{session.pulse?.round ?? '—'}</b> · open
          </p>
          <h1 className="headline">Nobody gets to know it was you.</h1>
          <p className="standfirst">
            Give a number from one to five. Your team gets a count of how many people are
            struggling. <strong>The number itself never leaves this device</strong> — not
            encrypted, not stored, not sent.
          </p>
          <p className="aside">
            A canary stops singing before anyone else notices the air has gone bad. That only
            works if it can answer honestly.
          </p>
        </CircuitCall>
      </main>

      <footer className="foot">
        Proofs are generated by your own wallet, on your own machine. No backend, no analytics, no
        third-party requests —{' '}
        <a
          href="https://github.com/EkinOnat/midnight-canary"
          target="_blank"
          rel="noreferrer noopener"
        >
          read the contract
        </a>
        .
      </footer>
    </div>
  );
}
